### ISSUE TITLE
Repo Funkiness

### ISSUE THREAD

**Issue by ronhowe** [swccgpc/holotable#126] opened 2021-03-03 12:15 UTC
I performed a git pull on this repo and git thinks I've made edits.

![image](https://user-images.githubusercontent.com/5210043/109804408-349cf080-7bf0-11eb-8157-0ba272021d81.png)

Something happened last night when new GIFs were added.

Anybody else seeing this?

**Comment by ronhowe** [comment] 2021-03-03 12:16
This is true even if I delete the folder on my hard drive and do a fresh clone.

Git immediately thinks these three files are edited.

**Comment by ronhowe** [comment] 2021-03-03 13:07
Also, every time I open Holotable, it wants to download and delete these same three files.

**Comment by ronhowe** [comment] 2021-03-03 13:08
![image](https://user-images.githubusercontent.com/5210043/109810456-8c8b2580-7bf7-11eb-9a06-1ff497017b0e.png)

![image](https://user-images.githubusercontent.com/5210043/109810495-96148d80-7bf7-11eb-9e87-0db839988622.png)

**Comment by DevoKun** [comment] 2021-03-03 13:36
The problem is that the `t_e3pO.gif` filename is conflicting with the `t_e3po.gif` filename.
The **large** file is `e3po.gif`, all lowercase: https://github.com/swccgpc/holotable/tree/master/Images-HT/starwars/CloudCity-Dark/large

When the **e3po** images were added manually, the large file was generated as `e3po.gif` and the small file was generated as `t_e3pO.gif`. the GitHub actions automatically generate missing `t_` files and commit them, so `t_e3po.gif` was missing and it was auto-created and committed.

Linux is a case insensitive filesystem, so it respects `t_e3pO.gif` and `t_e3po.gif` as different files. Windows is _not_ case insensitive, so it believes the files as the same and overwrites them. That's why you see the change in git.

Really what needs to happen is for someone with a machine that honors filename case to remove the crusty filenames so the proper ones can be used.

**Comment by ronhowe** [comment] 2021-03-03 13:37
I have an Ubuntu 18.04 dev virtual machine.  Would that work?  If so, I can take a crack at it tonight after work.

**Comment by ronhowe** [comment] 2021-03-03 13:55
My Linux box doesn't seem to complain.  I'll try to get this done and submit a PR tonight.

**Comment by DevoKun** [comment] 2021-03-03 14:01
Those files have been removed.

**Closed by DevoKun** 2021-03-03 14:01 UTC
